#!/usr/bin/perl -w
use strict;
use warnings;

use LWP  5.825;

my $url = "http://lenta.ru";
my $file = $ARGV[0];

my $ua = LWP::UserAgent->new;
$ua->proxy('http', 'http://localhost:9000/');
$HTTP::Request::Common::DYNAMIC_FILE_UPLOAD = 1;

use HTTP::Request::Common;
my $req = POST(
    $url,
    Content_Type => 'multipart/form-data',
    Content      => [ file => [$file] ],
);

## set up callback
#{
#    my $gen = $req->content();
#            die unless ref($gen) eq "CODE";
#    my $i = 0;
#    $req->content(
#        sub {
#            my $chunk = &$gen(); # get chunk of data
#            warn $i++;
#            return $chunk;       # send it to $url
#        }
#    );
#
##use Data::Dumper;die print Data::Dumper->new([($ua,$req, $gen)])->Indent(1)->Deparse(1)->Dump;
#}

my $res = $ua->request($req);   #do it 
print $res->status_line;